FROM cmd:v1
#EXPOSE instruction informs Docker that the container listens on the specified network ports at runtime. You can specify whether the port listens on TCP or UDP, and the default is TCP if the protocol is not specified. Thus, Writing EXPOSE in your Dockerfile, is merely a hint that a certain port is useful.
EXPOSE 80/tcp
