FROM almalinux:8
# A label is a key-value pair, stored as a string. You can specify multiple labels for an object, but each key must be unique within an object. If the same key is given multiple values, the most-recently-written value overwrites all previous values.
LABEL COURSE=TERRAFORM \
      TRAINEE=TRIVENI \
      AUTHOR="Triveni"