FROM almalinux:8
#RUN cd /tmp
# docker ignores previous cd command, every instruction it will assume it is home directory. /
# workdir is useful to set the path
WORKDIR /tmp
RUN touch workdir.txt 
RUN  touch hi.txt