FROM almalinux:8
# add is useful to  directly download the content  from internet.
ADD https://github.com/techworldwithsiva/docker-install-commands/blob/master/docker-install.sh /tmp/docker.sh
#and also add can untar the tar file and copy the contents directly into image. 
ADD sample-1.tar /tmp/

#COPY VS ADD
# copy and add both are useful to copy the files 
#but, add has some extra capabilities it can directly download the content  from internet and also it can untar the tar file and copy the contents directly into image.