FROM almalinux:8
#ENV files allow you to pass multiple environment variables at once. You can pass the . env file variables to the docker run command using the –env-file options, like so: docker run –env-file
ENV USERNAME=admin \
    PASSWORD=admin \
    PORT=3306 \
    HOSTNAME="mysql.com"